#' Run the Shiny app to interactively explore cell-cell interactions.
#'
#' @param INX The list containing edgelist and node metadata as generated by
#'   \code{\link{BuildCCInx}}.
#' @param imageFileType Default="pdf". The file format for saved figures. One of
#'   \code{"pdf"} (generated with \code{\link[grDevices]{cairo_pdf}}),
#'   \code{"eps"} (generated with \code{\link[grDevices]{cairo_ps}}),
#'   \code{"tiff"} (generated with \code{\link[grDevices]{tiff}}), or
#'   \code{"png"} (generated with \code{\link[grDevices]{png}}).
#' @param ... Named options that should be passed to the
#'   \code{\link[shiny]{runApp}} call (these can be any of the following:
#'   "port", "launch.browser", "host", "quiet", "display.mode" and "test.mode").
#'
#' @export

ViewCCInx <- function(INX,imageFileType="pdf",...) {
  if (!is.list(INX) |
      !all(grepl("~",names(INX))) |
      !all(sapply(INX,function(X) all(c("edges","nodes") %in% names(X))))) {
    stop("INX must be the output of the function CCInx::BuildCCInx()")
  }

  if (!imageFileType %in% c("pdf","eps","png","tiff")) {
    warning('imageFileType must be one of c("pdf","eps","png","tiff"). Setting to "pdf".')
    imageFileType <- "pdf"
  }

  ui <- pageWithSidebar(
    headerPanel("CCInx Viewer"),
    sidebarPanel(
      fluidRow(
        column(6,
               uiOutput("cellTypesA"),
               selectInput("proteinTypeB","Node Type B:",
                           choices=c("Receptor","Ligand","ECM"),selected="Ligand")
        ),
        column(6,
               uiOutput("cellTypesB"),
               selectInput("proteinTypeA","Node Type A:",
                           choices=c("Receptor","Ligand","ECM"),selected="Receptor")
        )
      ),
      fluidRow(
        column(4,
               radioButtons("WhichFilter","Filter nodes:",inline=F,
                            choices=c("All","Statistic","Magnitude","Top Edges","Genes"))
        ),
        column(8,
               uiOutput("Filter")
        )
      ),
      fluidRow(
        column(7,
               radioButtons("YSpacing","Y-axis:",inline=T,
                            choices=list(Relative="relative",
                                         Absolute="absolute"))
        ),
        column(5,
               downloadButton("PlotSave",paste("Save as",toupper(imageFileType))),
               align="right")
      )
      #### TESTING ####
      # textOutput("TEST")
    ),
    mainPanel(
      plotOutput("CCInx",height="800px")
    )
  )

  server <- function(input,output,session) {
    output$cellTypesA <- renderUI({
      temp <- unique(unlist(strsplit(names(INX),"~")))
      selectInput("cellTypeA","Cell Type A:",
                  choices=temp,selected=temp[1])
    })
    output$cellTypesB <- renderUI({
      temp <- unique(unlist(strsplit(names(INX),"~")))
      selectInput("cellTypeB","Cell Type B:",
                  choices=temp,selected=temp[2])
    })

    output$Filter <- renderUI({
      switch(input$WhichFilter,
             "Statistic"=numericInput("GeneStatistic",
                                 label=paste0("Maximum ",attr(temp_inx(),"GeneStatistic"),":"),
                                 value=0.05),
             "Magnitude"=numericInput("GeneMagnitude",
                                      label=paste0("Minumum absolute ",attr(temp_inx(),"GeneMagnitude"),":"),
                                      value=.1),
             "Top Edges"=numericInput("TopN",
                                  label=paste0("Top n edges by mean ",
                                               attr(temp_inx(),"GeneMagnitude"),
                                               " of nodes:"),
                                  value=20),
             "Genes"=selectInput("GeneNames",label="Search by gene symbols:",
                                 choices=temp_inx()$nodes$gene,multiple=T)
      )
    })

    temp_inx <- reactive({
      FilterInx_step1(INX,
                      cellTypeA=input$cellTypeA,
                      cellTypeB=input$cellTypeB,
                      proteinTypeA=input$proteinTypeA,
                      proteinTypeB=input$proteinTypeB)
    })

    temp_inx2 <- reactive({
      switch(input$WhichFilter,
             "All"=temp_inx(),
             "Statistic"=FilterInx_GeneStatistic(temp_inx(),input$GeneStatistic),
             "Magnitude"=FilterInx_GeneMagnitude(temp_inx(),input$GeneMagnitude),
             "Top Edges"=FilterInx_topN(temp_inx(),input$TopN),
             "Genes"=FilterInx_genenames(temp_inx(),
                                         unique(unlist(strsplit(input$GeneNames," |,"))))
      )
    })


    output$CCInx <- renderPlot({
      DoPlotInx(temp_inx2()) #,input$YSpacing)
    },res=96)

    output$PlotSave <- downloadHandler(
      filename=reactive({
        paste0("CCInx_",
               input$cellTypeA,"_",input$proteinTypeA,"_",
               input$cellTypeB,"_",input$proteinTypeB,
               ".",imageFileType)
      }),
      content=function(file) {
        switch(imageFileType,
               "pdf"=grDevices::cairo_pdf(file,height=8,width=7,fallback_resolution=600),
               "eps"=grDevices::cairo_ps(file,height=8,width=7,fallback_resolution=600),
               "tiff"=grDevices::tiff(file,height=8,width=7,units="in",res=600),
               "png"=grDevices::png(file,height=8,width=7,units="in",res=600))
        DoPlotInx(temp_inx2()) #,input$YSpacing)
        grDevices::dev.off()
      }
    )


    #### TESTING ####
    output$TEST <- renderPrint(paste0("CCInx_",
                                      input$cellTypeA,"_",input$proteinTypeA,"_",
                                      input$cellTypeB,"_",input$proteinTypeB,
                                      ".",imageFileType))
  }
  shinyApp(ui,server,options=list(...))
}
